#!/bin/sh
set -e
# Automatically added by dh_installmodules/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -e /boot/System.map-4.4.78-blackberry-athena ]; then
		depmod -a -F /boot/System.map-4.4.78-blackberry-athena 4.4.78-blackberry-athena || true
	fi
fi
# End automatically added section
